name: Enviar Aniversariantes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: |
          pip install pandas openpyxl sendgrid

      - name: Executar script
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python main.py
